import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeIdToUuid1692693259969 implements MigrationInterface {
    name = 'ChangeIdToUuid1692693259969'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "role" ADD "deleted_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "FK_6f05f9b90ea78c5623b9d9a8733"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_44fe9cb93426e3887ba77208c33"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_1c105b756816efbdeae09a9ab65"`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "FK_a4abe6e0c60678f43b269dde18d"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "FK_1a8686fe9fb466d2fcde46558f7"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "FK_e6bfe27d6f696c282de223b0e39"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "PK_a2d3e935a6591168066defec5ad"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "PK_a2d3e935a6591168066defec5ad" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "referred_by_id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "referred_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "UQ_1a8686fe9fb466d2fcde46558f7"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "address_id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "address_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "UQ_1a8686fe9fb466d2fcde46558f7" UNIQUE ("address_id")`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "role_id" uuid`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "opening_id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "opening_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_2a4f5082f1be346e2b8cdec2194"`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_94f5ee8ab01e6f404378b33456f"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_d62835db8c0aec1d18a5a927549"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "department_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "role_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "REL_2a4f5082f1be346e2b8cdec219"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "address_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "address_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "UQ_2a4f5082f1be346e2b8cdec2194" UNIQUE ("address_id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "REL_94f5ee8ab01e6f404378b33456"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "referred_by_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "referred_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "UQ_94f5ee8ab01e6f404378b33456f" UNIQUE ("referred_by_id")`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_e2bd9c0654a8573b246b633127b"`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "PK_9a2213262c1593bffb581e382f5"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "PK_9a2213262c1593bffb581e382f5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "PK_8b433fbb5ac3bc1cda8afc64fa2"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "opening" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "PK_8b433fbb5ac3bc1cda8afc64fa2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "opening" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "opening" ADD "department_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opening" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "opening" ADD "role_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "FK_a4abe6e0c60678f43b269dde18d" FOREIGN KEY ("referred_by_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "FK_1a8686fe9fb466d2fcde46558f7" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "FK_6f05f9b90ea78c5623b9d9a8733" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "FK_e6bfe27d6f696c282de223b0e39" FOREIGN KEY ("opening_id") REFERENCES "opening"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_d62835db8c0aec1d18a5a927549" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_1c105b756816efbdeae09a9ab65" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_2a4f5082f1be346e2b8cdec2194" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_94f5ee8ab01e6f404378b33456f" FOREIGN KEY ("referred_by_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_e2bd9c0654a8573b246b633127b" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_44fe9cb93426e3887ba77208c33" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_44fe9cb93426e3887ba77208c33"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "FK_e2bd9c0654a8573b246b633127b"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_94f5ee8ab01e6f404378b33456f"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_2a4f5082f1be346e2b8cdec2194"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_1c105b756816efbdeae09a9ab65"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "FK_d62835db8c0aec1d18a5a927549"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "FK_e6bfe27d6f696c282de223b0e39"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "FK_6f05f9b90ea78c5623b9d9a8733"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "FK_1a8686fe9fb466d2fcde46558f7"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "FK_a4abe6e0c60678f43b269dde18d"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "opening" ADD "role_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opening" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "opening" ADD "department_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opening" DROP CONSTRAINT "PK_8b433fbb5ac3bc1cda8afc64fa2"`);
        await queryRunner.query(`ALTER TABLE "opening" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "opening" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "PK_8b433fbb5ac3bc1cda8afc64fa2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "department" DROP CONSTRAINT "PK_9a2213262c1593bffb581e382f5"`);
        await queryRunner.query(`ALTER TABLE "department" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "department" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "department" ADD CONSTRAINT "PK_9a2213262c1593bffb581e382f5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_e2bd9c0654a8573b246b633127b" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "UQ_94f5ee8ab01e6f404378b33456f"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "referred_by_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "referred_by_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "REL_94f5ee8ab01e6f404378b33456" UNIQUE ("referred_by_id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "UQ_2a4f5082f1be346e2b8cdec2194"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "address_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "address_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "REL_2a4f5082f1be346e2b8cdec219" UNIQUE ("address_id")`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "role_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "department_id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "department_id" integer`);
        await queryRunner.query(`ALTER TABLE "employee" DROP CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498"`);
        await queryRunner.query(`ALTER TABLE "employee" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "employee" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "PK_3c2bc72f03fd5abbbc5ac169498" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_d62835db8c0aec1d18a5a927549" FOREIGN KEY ("department_id") REFERENCES "department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_94f5ee8ab01e6f404378b33456f" FOREIGN KEY ("referred_by_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "address" DROP CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5"`);
        await queryRunner.query(`ALTER TABLE "address" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "address" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "address" ADD CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_2a4f5082f1be346e2b8cdec2194" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "opening_id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "opening_id" integer`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "role_id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "role_id" integer`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "UQ_1a8686fe9fb466d2fcde46558f7"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "address_id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "address_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "UQ_1a8686fe9fb466d2fcde46558f7" UNIQUE ("address_id")`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "referred_by_id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "referred_by_id" integer`);
        await queryRunner.query(`ALTER TABLE "referral" DROP CONSTRAINT "PK_a2d3e935a6591168066defec5ad"`);
        await queryRunner.query(`ALTER TABLE "referral" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "referral" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "PK_a2d3e935a6591168066defec5ad" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "FK_e6bfe27d6f696c282de223b0e39" FOREIGN KEY ("opening_id") REFERENCES "opening"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "FK_1a8686fe9fb466d2fcde46558f7" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "FK_a4abe6e0c60678f43b269dde18d" FOREIGN KEY ("referred_by_id") REFERENCES "employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" DROP CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "role" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "role" ADD CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "employee" ADD CONSTRAINT "FK_1c105b756816efbdeae09a9ab65" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "opening" ADD CONSTRAINT "FK_44fe9cb93426e3887ba77208c33" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "referral" ADD CONSTRAINT "FK_6f05f9b90ea78c5623b9d9a8733" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "deleted_at"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "role" DROP COLUMN "created_at"`);
    }

}
